# Generated by Django 5.2.2 on 2025-06-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=50)),
                ('session_datetime', models.DateTimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('total_slots', models.IntegerField()),
            ],
            options={
                'unique_together': {('class_name', 'session_datetime')},
            },
        ),
    ]
